version: "3.9"

services:
  frontend:
    build: .
    container_name: movie-frontend
    expose:
      - "80"

  backend:
    build: ./backend
    expose:
      - "3000"

  proxy:
    build: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
