version: '3.9'

services:
  frontend:
    build: .
    container_name: movie-frontend
    expose:
      - '80'

  backend:
    build: ./backend
    expose:
      - '8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/film_review
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=prod
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: film_review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  proxy:
    build: ./proxy
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
